//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_tb
    {
        public int em_id { get; set; }
        public string fisrtname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public string role { get; set; }
        public string username { get; set; }
    }
}
