//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EFF
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_tb
    {
        public int req_id { get; set; }
        public string foodtype { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public string assing_employee { get; set; }
        public string details_food { get; set; }
        public Nullable<int> date_of_order { get; set; }
    }
}
