//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int restaurants_id { get; set; }
        public string rest_name { get; set; }
        public string rest_type { get; set; }
        public string res_location { get; set; }
        public string res_phone { get; set; }
        public string res_email { get; set; }
        public string res_username { get; set; }
        public string res_password { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
