//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ITEM_ID { get; set; }
        public string Quantity { get; set; }
        public string Subtotal { get; set; }
        public int OID { get; set; }
        public int PID { get; set; }
    }
}
